/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package biblioteca.vista;

import biblioteca.controlador.*;

/**
 *
 * @author arnal
 */
public class SistemaBibliotecas extends javax.swing.JFrame {
    
    public VDashboard dashboard;
    public VPrestamos prestamos;
    public VLibros libros;
    public VUsuarios usuarios;
    public VSedes sedes;
    public VReportes reportes;
    

    /**
     * Creates new form SistemaBibliotecas
     */
    public SistemaBibliotecas() {
        initComponents();
        
        dashboard = new VDashboard();
        prestamos = new VPrestamos();
        libros = new VLibros();
        usuarios = new CUsuarios(new VUsuarios()).vista;
        sedes = new VSedes();
        reportes = new VReportes();
        
        // Agregamoms al desktopPane
        pnlMain.add(dashboard);
        pnlMain.add(prestamos);
        pnlMain.add(libros);
        pnlMain.add(usuarios);
        pnlMain.add(sedes);
        pnlMain.add(reportes);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblSede = new javax.swing.JLabel();
        cbxSedes = new javax.swing.JComboBox<>();
        lblTitle = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnMenuDashboard = new javax.swing.JLabel();
        btnMenuPrestamos = new javax.swing.JLabel();
        btnMenuUsuarios = new javax.swing.JLabel();
        btnMenuSalir = new javax.swing.JLabel();
        btnMenuSedes = new javax.swing.JLabel();
        btnMenuLibros = new javax.swing.JLabel();
        btnMenuReportes = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA PARA UNA RED  DE BIBLIOTECAS");
        setBackground(new java.awt.Color(0, 255, 51));
        setLocation(new java.awt.Point(550, 150));
        setMinimumSize(new java.awt.Dimension(1216, 762));
        setName(""); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1216, 762));

        desktopPane.setMinimumSize(new java.awt.Dimension(1216, 762));
        desktopPane.setName(""); // NOI18N

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setAutoscrolls(true);
        jPanel1.setMinimumSize(new java.awt.Dimension(1216, 762));
        jPanel1.setPreferredSize(new java.awt.Dimension(1216, 762));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(204, 255, 255));
        pnlHeader.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        pnlHeader.setMinimumSize(new java.awt.Dimension(1000, 30));
        pnlHeader.setPreferredSize(new java.awt.Dimension(1000, 30));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSede.setBackground(new java.awt.Color(0, 102, 102));
        lblSede.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblSede.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSede.setText("SEDE");
        pnlHeader.add(lblSede, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        cbxSedes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxSedes.setBorder(null);
        cbxSedes.setMinimumSize(new java.awt.Dimension(43, 22));
        cbxSedes.setPreferredSize(new java.awt.Dimension(43, 22));
        pnlHeader.add(cbxSedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2, 210, 25));

        lblTitle.setBackground(new java.awt.Color(0, 102, 102));
        lblTitle.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("SISTEMA DE BIBLIOTECAS");
        pnlHeader.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 230, 30));

        jPanel1.add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 0, 1000, 30));

        pnlMenu.setBackground(new java.awt.Color(230, 255, 255));
        pnlMenu.setMinimumSize(new java.awt.Dimension(216, 762));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconLogo.png"))); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        btnMenuDashboard.setBackground(new java.awt.Color(230, 255, 255));
        btnMenuDashboard.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnMenuDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconDashboard.png"))); // NOI18N
        btnMenuDashboard.setText("DASHBOARD");
        btnMenuDashboard.setToolTipText("");
        btnMenuDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuDashboard.setOpaque(true);

        btnMenuPrestamos.setBackground(new java.awt.Color(230, 255, 255));
        btnMenuPrestamos.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnMenuPrestamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconTime.png"))); // NOI18N
        btnMenuPrestamos.setText("PRESTAMOS");
        btnMenuPrestamos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuPrestamos.setOpaque(true);

        btnMenuUsuarios.setBackground(new java.awt.Color(230, 255, 255));
        btnMenuUsuarios.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnMenuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconUsers.png"))); // NOI18N
        btnMenuUsuarios.setText("USUARIOS");
        btnMenuUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuUsuarios.setOpaque(true);

        btnMenuSalir.setBackground(new java.awt.Color(230, 255, 255));
        btnMenuSalir.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnMenuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconExit.png"))); // NOI18N
        btnMenuSalir.setText("SALIR");
        btnMenuSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuSalir.setOpaque(true);

        btnMenuSedes.setBackground(new java.awt.Color(230, 255, 255));
        btnMenuSedes.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnMenuSedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlace.png"))); // NOI18N
        btnMenuSedes.setText("SEDES");
        btnMenuSedes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuSedes.setOpaque(true);

        btnMenuLibros.setBackground(new java.awt.Color(230, 255, 255));
        btnMenuLibros.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnMenuLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconBooks.png"))); // NOI18N
        btnMenuLibros.setText("LIBROS");
        btnMenuLibros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuLibros.setOpaque(true);

        btnMenuReportes.setBackground(new java.awt.Color(230, 255, 255));
        btnMenuReportes.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnMenuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAnalytics.png"))); // NOI18N
        btnMenuReportes.setText("REPORTES");
        btnMenuReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuReportes.setOpaque(true);

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblLogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuDashboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(btnMenuLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuSedes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(btnMenuReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenuPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenuLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenuUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenuSedes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenuReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenuSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel1.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 216, 762));

        pnlMain.setBackground(new java.awt.Color(0, 51, 51));
        pnlMain.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 3, true));
        pnlMain.setMinimumSize(new java.awt.Dimension(1000, 732));
        pnlMain.setName(""); // NOI18N
        pnlMain.setPreferredSize(new java.awt.Dimension(1000, 732));
        pnlMain.setLayout(new java.awt.CardLayout());
        jPanel1.add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 30, 1000, 732));

        desktopPane.add(jPanel1);
        jPanel1.setBounds(0, 0, 1216, 762);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1216, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnMenuDashboard;
    public javax.swing.JLabel btnMenuLibros;
    public javax.swing.JLabel btnMenuPrestamos;
    public javax.swing.JLabel btnMenuReportes;
    public javax.swing.JLabel btnMenuSalir;
    public javax.swing.JLabel btnMenuSedes;
    public javax.swing.JLabel btnMenuUsuarios;
    public javax.swing.JComboBox<String> cbxSedes;
    public javax.swing.JDesktopPane desktopPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSede;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlHeader;
    public javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables

}
