/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package biblioteca.vista;

import biblioteca.controlador.*;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author arnal
 */
public class VPrestamos extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */

    public VPrestamos() {
        initComponents();
       formCreatePrestamo.setVisible(false);
      btnCrearPrestamo.setText("<html>NUEVO<br>PRESTAMO</html>");
      lblUserId.setVisible(false);
      lblUserEstado.setVisible(false);
      lblUserInfo.setText("");
      lblInfoFormCreatePrestamo.setText("");
      lblLibEstado.setVisible(false);
      lblLibId.setVisible(false);
      lblLibInfo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formCreatePrestamo = new javax.swing.JFrame();
        pnlCreatePrestamo = new javax.swing.JPanel();
        lblInfoFormCreatePrestamo = new javax.swing.JLabel();
        btnCancelCreatePrestamo = new javax.swing.JButton();
        btnCreatePrestamo = new javax.swing.JButton();
        btnCleanFormPrestamo = new javax.swing.JButton();
        pnlLib = new javax.swing.JPanel();
        txtLibSearch = new javax.swing.JTextField();
        lblTitle1 = new javax.swing.JLabel();
        lblLibId = new javax.swing.JLabel();
        lblLibEstado = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        txtLibTitulo = new javax.swing.JTextField();
        lblCedula1 = new javax.swing.JLabel();
        txtLibCodigo = new javax.swing.JTextField();
        txtLibAutor = new javax.swing.JTextField();
        lblCategoria3 = new javax.swing.JLabel();
        lblCategoria4 = new javax.swing.JLabel();
        txtLibCategoria = new javax.swing.JTextField();
        txtLibUbicacion = new javax.swing.JTextField();
        lblCategoria5 = new javax.swing.JLabel();
        btnLibSearch = new javax.swing.JButton();
        lblLibInfo = new javax.swing.JLabel();
        pnlUser = new javax.swing.JPanel();
        txtUserSearch = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblUserId = new javax.swing.JLabel();
        lblUserEstado = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtUserNombre = new javax.swing.JTextField();
        lblCedula = new javax.swing.JLabel();
        txtUserCedula = new javax.swing.JTextField();
        txtUserCategoria = new javax.swing.JTextField();
        lblCategoria = new javax.swing.JLabel();
        lblCategoria1 = new javax.swing.JLabel();
        txtUserCurso = new javax.swing.JTextField();
        txtUserEstado = new javax.swing.JTextField();
        lblCategoria2 = new javax.swing.JLabel();
        btnUserSearch = new javax.swing.JButton();
        lblUserInfo = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        pnlBackground = new javax.swing.JPanel();
        checkEstado = new javax.swing.JCheckBox();
        btnRecepcionarPrestamo = new javax.swing.JButton();
        btnEliminarPrestamo = new javax.swing.JButton();
        btnCrearPrestamo = new javax.swing.JButton();
        txtSearchPrestamo = new javax.swing.JTextField();
        btnSearch = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrestamos = new javax.swing.JTable();

        formCreatePrestamo.setLocation(new java.awt.Point(782, 186));
        formCreatePrestamo.setMinimumSize(new java.awt.Dimension(619, 680));
        formCreatePrestamo.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        formCreatePrestamo.setPreferredSize(new java.awt.Dimension(619, 680));
        formCreatePrestamo.setResizable(false);
        formCreatePrestamo.setSize(new java.awt.Dimension(619, 680));
        formCreatePrestamo.setType(java.awt.Window.Type.POPUP);

        pnlCreatePrestamo.setBackground(new java.awt.Color(255, 255, 255));
        pnlCreatePrestamo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInfoFormCreatePrestamo.setForeground(new java.awt.Color(255, 0, 51));
        lblInfoFormCreatePrestamo.setText("* ");
        pnlCreatePrestamo.add(lblInfoFormCreatePrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 580, 50));

        btnCancelCreatePrestamo.setBackground(new java.awt.Color(102, 0, 0));
        btnCancelCreatePrestamo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCancelCreatePrestamo.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelCreatePrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconCancel.png"))); // NOI18N
        btnCancelCreatePrestamo.setText("CANCELAR");
        btnCancelCreatePrestamo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelCreatePrestamo.setIconTextGap(10);
        btnCancelCreatePrestamo.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnCancelCreatePrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelCreatePrestamoMouseClicked(evt);
            }
        });
        pnlCreatePrestamo.add(btnCancelCreatePrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 160, 40));

        btnCreatePrestamo.setBackground(new java.awt.Color(153, 255, 153));
        btnCreatePrestamo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnCreatePrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnCreatePrestamo.setText("CREAR PRESTAMO");
        btnCreatePrestamo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCreatePrestamo.setIconTextGap(10);
        btnCreatePrestamo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCreatePrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreatePrestamoMouseClicked(evt);
            }
        });
        pnlCreatePrestamo.add(btnCreatePrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 590, 190, 40));

        btnCleanFormPrestamo.setBackground(new java.awt.Color(230, 230, 230));
        btnCleanFormPrestamo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCleanFormPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconMop.png"))); // NOI18N
        btnCleanFormPrestamo.setText("LIMPIAR");
        btnCleanFormPrestamo.setToolTipText("");
        btnCleanFormPrestamo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCleanFormPrestamo.setIconTextGap(10);
        btnCleanFormPrestamo.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnCleanFormPrestamo.setMaximumSize(new java.awt.Dimension(125, 35));
        btnCleanFormPrestamo.setMinimumSize(new java.awt.Dimension(125, 35));
        btnCleanFormPrestamo.setPreferredSize(new java.awt.Dimension(125, 35));
        btnCleanFormPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCleanFormPrestamoMouseClicked(evt);
            }
        });
        pnlCreatePrestamo.add(btnCleanFormPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 590, 160, 40));

        txtLibSearch.setBorder(null);
        txtLibSearch.setMargin(new java.awt.Insets(0, 10, 0, 0));
        txtLibSearch.setOpaque(true);
        txtLibSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLibSearchKeyTyped(evt);
            }
        });

        lblTitle1.setFont(new java.awt.Font("Roboto Black", 3, 24)); // NOI18N
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("SELECCIONAR LIBRO");

        lblLibId.setBackground(new java.awt.Color(255, 255, 204));
        lblLibId.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblLibId.setForeground(new java.awt.Color(255, 255, 204));
        lblLibId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLibId.setText("0");
        lblLibId.setToolTipText("");
        lblLibId.setEnabled(false);
        lblLibId.setFocusable(false);

        lblLibEstado.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblLibEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLibEstado.setText("0");
        lblLibEstado.setEnabled(false);

        lblNombre1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblNombre1.setText("TITULO");

        txtLibTitulo.setBackground(new java.awt.Color(255, 255, 204));
        txtLibTitulo.setBorder(null);
        txtLibTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLibTitulo.setEnabled(false);
        txtLibTitulo.setOpaque(true);

        lblCedula1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCedula1.setText("CODIGO");

        txtLibCodigo.setBackground(new java.awt.Color(255, 255, 204));
        txtLibCodigo.setBorder(null);
        txtLibCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLibCodigo.setEnabled(false);
        txtLibCodigo.setOpaque(true);

        txtLibAutor.setBackground(new java.awt.Color(255, 255, 204));
        txtLibAutor.setBorder(null);
        txtLibAutor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLibAutor.setEnabled(false);
        txtLibAutor.setOpaque(true);

        lblCategoria3.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria3.setText("AUTOR");

        lblCategoria4.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria4.setText("CATEGORIA");

        txtLibCategoria.setBackground(new java.awt.Color(255, 255, 204));
        txtLibCategoria.setBorder(null);
        txtLibCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLibCategoria.setEnabled(false);
        txtLibCategoria.setOpaque(true);

        txtLibUbicacion.setBackground(new java.awt.Color(255, 255, 204));
        txtLibUbicacion.setBorder(null);
        txtLibUbicacion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLibUbicacion.setEnabled(false);
        txtLibUbicacion.setOpaque(true);

        lblCategoria5.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria5.setText("UBICACION");

        btnLibSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnLibSearch.setBorder(null);
        btnLibSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLibSearchMouseClicked(evt);
            }
        });

        lblLibInfo.setForeground(new java.awt.Color(255, 0, 51));
        lblLibInfo.setText("* ");

        javax.swing.GroupLayout pnlLibLayout = new javax.swing.GroupLayout(pnlLib);
        pnlLib.setLayout(pnlLibLayout);
        pnlLibLayout.setHorizontalGroup(
            pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLibLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLibLayout.createSequentialGroup()
                        .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoria3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoria4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoria5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlLibLayout.createSequentialGroup()
                        .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtLibUbicacion)
                            .addComponent(txtLibCategoria)
                            .addComponent(txtLibAutor)
                            .addComponent(txtLibTitulo)
                            .addComponent(txtLibCodigo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLibLayout.createSequentialGroup()
                                .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlLibLayout.createSequentialGroup()
                                        .addComponent(lblCedula1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblLibEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtLibSearch))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLibId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLibSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(pnlLibLayout.createSequentialGroup()
                        .addComponent(lblLibInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlLibLayout.setVerticalGroup(
            pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLibLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLibSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLibSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(lblLibInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLibId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLibEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCedula1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLibCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNombre1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLibTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCategoria3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLibAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCategoria4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLibCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCategoria5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLibUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnlCreatePrestamo.add(pnlLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 290, 510));

        txtUserSearch.setBorder(null);
        txtUserSearch.setMargin(new java.awt.Insets(0, 10, 0, 0));
        txtUserSearch.setOpaque(true);
        txtUserSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserSearchKeyTyped(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Roboto Black", 3, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("SELECCIONAR USUARIO");

        lblUserId.setBackground(new java.awt.Color(255, 255, 204));
        lblUserId.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblUserId.setForeground(new java.awt.Color(255, 255, 204));
        lblUserId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserId.setText("0");
        lblUserId.setToolTipText("");
        lblUserId.setEnabled(false);
        lblUserId.setFocusable(false);

        lblUserEstado.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblUserEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserEstado.setText("0");
        lblUserEstado.setEnabled(false);

        lblNombre.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblNombre.setText("NOMBRES");

        txtUserNombre.setBackground(new java.awt.Color(255, 255, 204));
        txtUserNombre.setBorder(null);
        txtUserNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUserNombre.setEnabled(false);
        txtUserNombre.setOpaque(true);

        lblCedula.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCedula.setText("CEDULA");

        txtUserCedula.setBackground(new java.awt.Color(255, 255, 204));
        txtUserCedula.setBorder(null);
        txtUserCedula.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUserCedula.setEnabled(false);
        txtUserCedula.setOpaque(true);

        txtUserCategoria.setBackground(new java.awt.Color(255, 255, 204));
        txtUserCategoria.setBorder(null);
        txtUserCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUserCategoria.setEnabled(false);
        txtUserCategoria.setOpaque(true);

        lblCategoria.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria.setText("CATEGORIA");

        lblCategoria1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria1.setText("CURSO");

        txtUserCurso.setBackground(new java.awt.Color(255, 255, 204));
        txtUserCurso.setBorder(null);
        txtUserCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUserCurso.setEnabled(false);
        txtUserCurso.setOpaque(true);

        txtUserEstado.setBackground(new java.awt.Color(255, 255, 204));
        txtUserEstado.setBorder(null);
        txtUserEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUserEstado.setEnabled(false);
        txtUserEstado.setOpaque(true);

        lblCategoria2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria2.setText("ESTADO");

        btnUserSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnUserSearch.setBorder(null);
        btnUserSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserSearchMouseClicked(evt);
            }
        });

        lblUserInfo.setForeground(new java.awt.Color(255, 0, 51));
        lblUserInfo.setText("* ");

        javax.swing.GroupLayout pnlUserLayout = new javax.swing.GroupLayout(pnlUser);
        pnlUser.setLayout(pnlUserLayout);
        pnlUserLayout.setHorizontalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUserLayout.createSequentialGroup()
                        .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlUserLayout.createSequentialGroup()
                        .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUserCedula)
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUserEstado)
                            .addComponent(txtUserCurso)
                            .addComponent(txtUserCategoria)
                            .addComponent(txtUserNombre)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserLayout.createSequentialGroup()
                                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlUserLayout.createSequentialGroup()
                                        .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblUserEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtUserSearch))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUserSearch, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addContainerGap())))
        );
        pnlUserLayout.setVerticalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUserSearch))
                .addGap(12, 12, 12)
                .addComponent(lblUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCedula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCategoria1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCategoria2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pnlCreatePrestamo.add(pnlUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 510));

        javax.swing.GroupLayout formCreatePrestamoLayout = new javax.swing.GroupLayout(formCreatePrestamo.getContentPane());
        formCreatePrestamo.getContentPane().setLayout(formCreatePrestamoLayout);
        formCreatePrestamoLayout.setHorizontalGroup(
            formCreatePrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formCreatePrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCreatePrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        formCreatePrestamoLayout.setVerticalGroup(
            formCreatePrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formCreatePrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCreatePrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        formCreatePrestamo.getAccessibleContext().setAccessibleParent(pnlMain);

        setMinimumSize(new java.awt.Dimension(684, 694));
        setPreferredSize(new java.awt.Dimension(684, 694));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMain.setPreferredSize(new java.awt.Dimension(684, 694));
        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackground.setMinimumSize(new java.awt.Dimension(684, 685));
        pnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkEstado.setText("EN CURSO");
        checkEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkEstadoItemStateChanged(evt);
            }
        });
        pnlBackground.add(checkEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        btnRecepcionarPrestamo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnRecepcionarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconBookmarkAdd.png"))); // NOI18N
        btnRecepcionarPrestamo.setText("RECEPCIONAR");
        btnRecepcionarPrestamo.setToolTipText("");
        btnRecepcionarPrestamo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRecepcionarPrestamo.setIconTextGap(10);
        btnRecepcionarPrestamo.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnRecepcionarPrestamo.setMaximumSize(new java.awt.Dimension(125, 35));
        btnRecepcionarPrestamo.setMinimumSize(new java.awt.Dimension(125, 35));
        btnRecepcionarPrestamo.setPreferredSize(new java.awt.Dimension(125, 35));
        btnRecepcionarPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecepcionarPrestamoMouseClicked(evt);
            }
        });
        pnlBackground.add(btnRecepcionarPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 160, 40));

        btnEliminarPrestamo.setBackground(new java.awt.Color(102, 0, 0));
        btnEliminarPrestamo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnEliminarPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconTrash.png"))); // NOI18N
        btnEliminarPrestamo.setText("ELIMINAR");
        btnEliminarPrestamo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEliminarPrestamo.setIconTextGap(10);
        btnEliminarPrestamo.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnEliminarPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarPrestamoMouseClicked(evt);
            }
        });
        pnlBackground.add(btnEliminarPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 680, 160, 40));

        btnCrearPrestamo.setBackground(new java.awt.Color(153, 255, 153));
        btnCrearPrestamo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnCrearPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnCrearPrestamo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCrearPrestamo.setIconTextGap(10);
        btnCrearPrestamo.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnCrearPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearPrestamoMouseClicked(evt);
            }
        });
        pnlBackground.add(btnCrearPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 160, 60));

        txtSearchPrestamo.setBackground(new java.awt.Color(242, 242, 242));
        txtSearchPrestamo.setBorder(null);
        txtSearchPrestamo.setMargin(new java.awt.Insets(0, 10, 0, 0));
        txtSearchPrestamo.setOpaque(true);
        txtSearchPrestamo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchPrestamoKeyTyped(evt);
            }
        });
        pnlBackground.add(txtSearchPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 40));

        btnSearch.setBackground(new java.awt.Color(242, 242, 242));
        btnSearch.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.setOpaque(true);
        pnlBackground.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 40, 40));

        tblPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPrestamos);

        pnlBackground.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 980, 550));

        pnlMain.add(pnlBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 740));

        add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 730));
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserSearchKeyTyped
        // TODO add your handling code here:
        ((AbstractDocument) txtUserSearch.getDocument()).setDocumentFilter(new Validaciones.filtroNumerico());
    }//GEN-LAST:event_txtUserSearchKeyTyped
    
    private void txtLibSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLibSearchKeyTyped
        // TODO add your handling code here:
        ((AbstractDocument) txtLibSearch.getDocument()).setDocumentFilter(new Validaciones.filtroNumerico());
    }//GEN-LAST:event_txtLibSearchKeyTyped

    private void btnUserSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserSearchMouseClicked
        // TODO add your handling code here:
        
        new VFuncionesPrestamos().limpiar(txtUserCedula, txtUserCedula, txtUserNombre, txtUserCategoria, txtUserCurso, txtUserEstado, lblUserEstado, lblUserId, lblUserInfo, lblInfoFormCreatePrestamo);

        new VFuncionesPrestamos().buscarCedula(txtUserSearch,
         txtUserCedula,
          txtUserNombre,
           txtUserCategoria,
            txtUserCurso,
             txtUserEstado,
              lblUserId,
               lblUserEstado,
               lblUserInfo,
               lblInfoFormCreatePrestamo);
        
        
        
        
    }//GEN-LAST:event_btnUserSearchMouseClicked

    private void btnLibSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibSearchMouseClicked
        // TODO add your handling code here:

        new VFuncionesPrestamos().limpiar(txtLibCodigo, txtLibCodigo, txtLibTitulo, txtLibAutor, txtLibCategoria, txtLibUbicacion, lblLibEstado, lblLibId, lblLibInfo, lblInfoFormCreatePrestamo);

        new VFuncionesPrestamos().buscarLibro(txtLibSearch,
         txtLibCodigo,
         txtLibTitulo,
         txtLibAutor,
         txtLibCategoria,
         txtLibUbicacion,
         lblLibId,
         lblLibEstado,
         lblLibInfo,
         lblInfoFormCreatePrestamo);
        

    }//GEN-LAST:event_btnLibSearchMouseClicked

    private void btnCancelCreatePrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelCreatePrestamoMouseClicked
        // TODO add your handling code here:

        formCreatePrestamo.setVisible(false);
        new VFuncionesPrestamos().limpiar(txtUserSearch, txtUserCedula, txtUserNombre, txtUserCategoria, txtUserCurso, txtUserEstado, lblUserEstado, lblUserId, lblUserInfo, lblInfoFormCreatePrestamo);
        new VFuncionesPrestamos().limpiar(txtLibSearch, txtLibCodigo, txtLibTitulo, txtLibAutor, txtLibCategoria, txtLibUbicacion, lblLibEstado, lblLibId, lblLibInfo, lblInfoFormCreatePrestamo);

    }//GEN-LAST:event_btnCancelCreatePrestamoMouseClicked

    private void btnCleanFormPrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCleanFormPrestamoMouseClicked
        // TODO add your handling code here:

        new VFuncionesPrestamos().limpiar(txtUserSearch, txtUserCedula, txtUserNombre, txtUserCategoria, txtUserCurso, txtUserEstado, lblUserEstado, lblUserId, lblUserInfo, lblInfoFormCreatePrestamo);
        new VFuncionesPrestamos().limpiar(txtLibSearch, txtLibCodigo, txtLibTitulo, txtLibAutor, txtLibCategoria, txtLibUbicacion, lblLibEstado, lblLibId, lblLibInfo, lblInfoFormCreatePrestamo);
    }//GEN-LAST:event_btnCleanFormPrestamoMouseClicked

    private void btnCreatePrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreatePrestamoMouseClicked
        // TODO add your handling code here:

        new VFuncionesPrestamos().crearPrestamo(lblLibId, lblUserId, lblInfoFormCreatePrestamo);
        new VFuncionesPrestamos().limpiar(txtUserSearch, txtUserCedula, txtUserNombre, txtUserCategoria, txtUserCurso, txtUserEstado, lblUserEstado, lblUserId, lblUserInfo, lblUserInfo);
        new VFuncionesPrestamos().limpiar(txtLibSearch, txtLibCodigo, txtLibTitulo, txtLibAutor, txtLibCategoria, txtLibUbicacion, lblLibEstado, lblLibId, lblLibInfo, lblLibInfo);
        new VFuncionesPrestamos().mostrarPrestamos(tblPrestamos);

    }//GEN-LAST:event_btnCreatePrestamoMouseClicked

    private void btnCrearPrestamoMouseClicked(java.awt.event.MouseEvent evt) {
        
        
        formCreatePrestamo.setVisible(true);

        // cargarFormCrear();
    }

    private void btnRecepcionarPrestamoMouseClicked(java.awt.event.MouseEvent evt) {
        
        new VFuncionesPrestamos().recepcionarPrestamo(tblPrestamos);
        new VFuncionesPrestamos().mostrarPrestamos(tblPrestamos);
        
    }

    private void btnEliminarPrestamoMouseClicked(java.awt.event.MouseEvent evt) {
        
        new VFuncionesPrestamos().eliminarPrestamo(tblPrestamos);
        new VFuncionesPrestamos().mostrarPrestamos(tblPrestamos);
    }
    
    private void txtSearchPrestamoKeyTyped(java.awt.event.KeyEvent evt) {
        
        ((AbstractDocument) txtSearchPrestamo.getDocument()).setDocumentFilter(new Validaciones.filtroAlphaNumerico());
        
        if (checkEstado.isSelected()){
            new VFuncionesPrestamos().filtrarTabla(tblPrestamos,"EN CURSO", txtSearchPrestamo.getText() );
        }else new VFuncionesPrestamos().filtrarTabla(tblPrestamos,txtSearchPrestamo.getText(),"");
        
    }

    private void formComponentShown(java.awt.event.ComponentEvent evt) {
        
        new VFuncionesPrestamos().mostrarPrestamos(tblPrestamos);
    }

    private void checkEstadoItemStateChanged(java.awt.event.ItemEvent evt) {
        
        if (checkEstado.isSelected()){
            new VFuncionesPrestamos().filtrarTabla(tblPrestamos,"EN CURSO", txtSearchPrestamo.getText() );
        }else new VFuncionesPrestamos().filtrarTabla(tblPrestamos,txtSearchPrestamo.getText(),"");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelCreatePrestamo;
    private javax.swing.JButton btnCleanFormPrestamo;
    private javax.swing.JButton btnCrearPrestamo;
    private javax.swing.JButton btnCreatePrestamo;
    private javax.swing.JButton btnEliminarPrestamo;
    private javax.swing.JButton btnLibSearch;
    private javax.swing.JButton btnRecepcionarPrestamo;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JButton btnUserSearch;
    private javax.swing.JCheckBox checkEstado;
    private javax.swing.JFrame formCreatePrestamo;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JLabel lblCategoria;
    protected javax.swing.JLabel lblCategoria1;
    protected javax.swing.JLabel lblCategoria2;
    protected javax.swing.JLabel lblCategoria3;
    protected javax.swing.JLabel lblCategoria4;
    protected javax.swing.JLabel lblCategoria5;
    protected javax.swing.JLabel lblCedula;
    protected javax.swing.JLabel lblCedula1;
    protected javax.swing.JLabel lblInfoFormCreatePrestamo;
    protected javax.swing.JLabel lblLibEstado;
    protected javax.swing.JLabel lblLibId;
    protected javax.swing.JLabel lblLibInfo;
    protected javax.swing.JLabel lblNombre;
    protected javax.swing.JLabel lblNombre1;
    protected javax.swing.JLabel lblTitle;
    protected javax.swing.JLabel lblTitle1;
    protected javax.swing.JLabel lblUserEstado;
    protected javax.swing.JLabel lblUserId;
    protected javax.swing.JLabel lblUserInfo;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlCreatePrestamo;
    private javax.swing.JPanel pnlLib;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlUser;
    private javax.swing.JTable tblPrestamos;
    protected javax.swing.JTextField txtLibAutor;
    protected javax.swing.JTextField txtLibCategoria;
    protected javax.swing.JTextField txtLibCodigo;
    protected javax.swing.JTextField txtLibSearch;
    protected javax.swing.JTextField txtLibTitulo;
    protected javax.swing.JTextField txtLibUbicacion;
    protected javax.swing.JTextField txtSearchPrestamo;
    protected javax.swing.JTextField txtUserCategoria;
    protected javax.swing.JTextField txtUserCedula;
    protected javax.swing.JTextField txtUserCurso;
    protected javax.swing.JTextField txtUserEstado;
    protected javax.swing.JTextField txtUserNombre;
    protected javax.swing.JTextField txtUserSearch;
    // End of variables declaration//GEN-END:variables
}
