/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package biblioteca.vista;

import biblioteca.controlador.*;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

import javax.swing.text.AbstractDocument;

/**
 *
 * @author arnal
 */
public class VPrestamos extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */

    public VPrestamos() {
        initComponents();
       formCreatePrestamo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formCreatePrestamo = new javax.swing.JFrame();
        pnlCreatePrestamo = new javax.swing.JPanel();
        lblInfoFormCreatePrestamo = new javax.swing.JLabel();
        btnCancelCreatePrestamo = new javax.swing.JButton();
        btnCreatePrestamo = new javax.swing.JButton();
        btnCleanFormPrestamo = new javax.swing.JButton();
        pnlLib = new javax.swing.JPanel();
        txtLibSearch = new javax.swing.JTextField();
        lblTitle1 = new javax.swing.JLabel();
        lblLibId = new javax.swing.JLabel();
        lblLibEstado = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        txtLibTitulo = new javax.swing.JTextField();
        lblCedula1 = new javax.swing.JLabel();
        txtLibCodigo = new javax.swing.JTextField();
        txtLibAutor = new javax.swing.JTextField();
        lblCategoria3 = new javax.swing.JLabel();
        lblCategoria4 = new javax.swing.JLabel();
        txtLibCategoria = new javax.swing.JTextField();
        txtLibUbicacion = new javax.swing.JTextField();
        lblCategoria5 = new javax.swing.JLabel();
        btnLibSearch = new javax.swing.JButton();
        lblLibInfo = new javax.swing.JLabel();
        pnlUser = new javax.swing.JPanel();
        txtUserSearch = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblUserId = new javax.swing.JLabel();
        lblUserEstado = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtUserNombre = new javax.swing.JTextField();
        lblCedula = new javax.swing.JLabel();
        txtUserCedula = new javax.swing.JTextField();
        txtUserCategoria = new javax.swing.JTextField();
        lblCategoria = new javax.swing.JLabel();
        lblCategoria1 = new javax.swing.JLabel();
        txtUserCurso = new javax.swing.JTextField();
        txtUserEstado = new javax.swing.JTextField();
        lblCategoria2 = new javax.swing.JLabel();
        btnUserSearch = new javax.swing.JButton();
        lblUserInfo = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        pnlBackground = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        btnEditarUsuario = new javax.swing.JButton();
        btnEliminarUsuario = new javax.swing.JButton();
        btnCrearUsuario = new javax.swing.JButton();
        txfSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        formCreatePrestamo.setLocation(new java.awt.Point(782, 186));
        formCreatePrestamo.setMinimumSize(new java.awt.Dimension(619, 680));
        formCreatePrestamo.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        formCreatePrestamo.setPreferredSize(new java.awt.Dimension(619, 680));
        formCreatePrestamo.setResizable(false);
        formCreatePrestamo.setSize(new java.awt.Dimension(619, 680));
        formCreatePrestamo.setType(java.awt.Window.Type.POPUP);

        pnlCreatePrestamo.setBackground(new java.awt.Color(255, 255, 255));
        pnlCreatePrestamo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInfoFormCreatePrestamo.setForeground(new java.awt.Color(255, 0, 51));
        lblInfoFormCreatePrestamo.setText("* ");
        pnlCreatePrestamo.add(lblInfoFormCreatePrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 580, 50));

        btnCancelCreatePrestamo.setBackground(new java.awt.Color(102, 0, 0));
        btnCancelCreatePrestamo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCancelCreatePrestamo.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelCreatePrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconCancel.png"))); // NOI18N
        btnCancelCreatePrestamo.setText("CANCELAR");
        btnCancelCreatePrestamo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelCreatePrestamo.setIconTextGap(10);
        btnCancelCreatePrestamo.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnCancelCreatePrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelCreatePrestamoMouseClicked(evt);
            }
        });
        pnlCreatePrestamo.add(btnCancelCreatePrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 160, 40));

        btnCreatePrestamo.setBackground(new java.awt.Color(153, 255, 153));
        btnCreatePrestamo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnCreatePrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnCreatePrestamo.setText("CREAR PRESTAMO");
        btnCreatePrestamo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCreatePrestamo.setIconTextGap(10);
        btnCreatePrestamo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCreatePrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreatePrestamoMouseClicked(evt);
            }
        });
        btnCreatePrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePrestamoActionPerformed(evt);
            }
        });
        pnlCreatePrestamo.add(btnCreatePrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 590, 190, 40));

        btnCleanFormPrestamo.setBackground(new java.awt.Color(230, 230, 230));
        btnCleanFormPrestamo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCleanFormPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconMop.png"))); // NOI18N
        btnCleanFormPrestamo.setText("LIMPIAR");
        btnCleanFormPrestamo.setToolTipText("");
        btnCleanFormPrestamo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCleanFormPrestamo.setIconTextGap(10);
        btnCleanFormPrestamo.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnCleanFormPrestamo.setMaximumSize(new java.awt.Dimension(125, 35));
        btnCleanFormPrestamo.setMinimumSize(new java.awt.Dimension(125, 35));
        btnCleanFormPrestamo.setPreferredSize(new java.awt.Dimension(125, 35));
        btnCleanFormPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCleanFormPrestamoMouseClicked(evt);
            }
        });
        btnCleanFormPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanFormPrestamoActionPerformed(evt);
            }
        });
        pnlCreatePrestamo.add(btnCleanFormPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 590, 160, 40));

        txtLibSearch.setBorder(null);
        txtLibSearch.setMargin(new java.awt.Insets(0, 10, 0, 0));
        txtLibSearch.setOpaque(true);
        txtLibSearch.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtLibSearchInputMethodTextChanged(evt);
            }
        });
        txtLibSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLibSearchActionPerformed(evt);
            }
        });
        txtLibSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLibSearchKeyTyped(evt);
            }
        });

        lblTitle1.setFont(new java.awt.Font("Roboto Black", 3, 24)); // NOI18N
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("SELECCIONAR LIBRO");

        lblLibId.setBackground(new java.awt.Color(255, 255, 204));
        lblLibId.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblLibId.setForeground(new java.awt.Color(255, 255, 204));
        lblLibId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLibId.setText("0");
        lblLibId.setToolTipText("");
        lblLibId.setEnabled(false);
        lblLibId.setFocusable(false);

        lblLibEstado.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblLibEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLibEstado.setText("0");
        lblLibEstado.setEnabled(false);

        lblNombre1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblNombre1.setText("TITULO");

        txtLibTitulo.setBackground(new java.awt.Color(255, 255, 204));
        txtLibTitulo.setBorder(null);
        txtLibTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLibTitulo.setEnabled(false);
        txtLibTitulo.setOpaque(true);

        lblCedula1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCedula1.setText("CODIGO");

        txtLibCodigo.setBackground(new java.awt.Color(255, 255, 204));
        txtLibCodigo.setBorder(null);
        txtLibCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLibCodigo.setEnabled(false);
        txtLibCodigo.setOpaque(true);

        txtLibAutor.setBackground(new java.awt.Color(255, 255, 204));
        txtLibAutor.setBorder(null);
        txtLibAutor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLibAutor.setEnabled(false);
        txtLibAutor.setOpaque(true);

        lblCategoria3.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria3.setText("AUTOR");

        lblCategoria4.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria4.setText("CATEGORIA");

        txtLibCategoria.setBackground(new java.awt.Color(255, 255, 204));
        txtLibCategoria.setBorder(null);
        txtLibCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLibCategoria.setEnabled(false);
        txtLibCategoria.setOpaque(true);

        txtLibUbicacion.setBackground(new java.awt.Color(255, 255, 204));
        txtLibUbicacion.setBorder(null);
        txtLibUbicacion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLibUbicacion.setEnabled(false);
        txtLibUbicacion.setOpaque(true);

        lblCategoria5.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria5.setText("UBICACION");

        btnLibSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnLibSearch.setBorder(null);

        lblLibInfo.setForeground(new java.awt.Color(255, 0, 51));
        lblLibInfo.setText("* ");

        javax.swing.GroupLayout pnlLibLayout = new javax.swing.GroupLayout(pnlLib);
        pnlLib.setLayout(pnlLibLayout);
        pnlLibLayout.setHorizontalGroup(
            pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLibLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLibLayout.createSequentialGroup()
                        .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoria3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoria4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoria5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlLibLayout.createSequentialGroup()
                        .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtLibUbicacion)
                            .addComponent(txtLibCategoria)
                            .addComponent(txtLibAutor)
                            .addComponent(txtLibTitulo)
                            .addComponent(txtLibCodigo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLibLayout.createSequentialGroup()
                                .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlLibLayout.createSequentialGroup()
                                        .addComponent(lblCedula1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblLibEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtLibSearch))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLibId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLibSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(pnlLibLayout.createSequentialGroup()
                        .addComponent(lblLibInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlLibLayout.setVerticalGroup(
            pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLibLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLibSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLibSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(lblLibInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLibId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLibEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCedula1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLibCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNombre1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLibTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCategoria3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLibAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCategoria4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLibCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCategoria5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLibUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnlCreatePrestamo.add(pnlLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 290, 510));

        txtUserSearch.setBorder(null);
        txtUserSearch.setMargin(new java.awt.Insets(0, 10, 0, 0));
        txtUserSearch.setOpaque(true);
        txtUserSearch.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtUserSearchInputMethodTextChanged(evt);
            }
        });
        txtUserSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserSearchActionPerformed(evt);
            }
        });
        txtUserSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserSearchKeyTyped(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Roboto Black", 3, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("SELECCIONAR USUARIO");

        lblUserId.setBackground(new java.awt.Color(255, 255, 204));
        lblUserId.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblUserId.setForeground(new java.awt.Color(255, 255, 204));
        lblUserId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserId.setText("0");
        lblUserId.setToolTipText("");
        lblUserId.setEnabled(false);
        lblUserId.setFocusable(false);

        lblUserEstado.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblUserEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserEstado.setText("0");
        lblUserEstado.setEnabled(false);

        lblNombre.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblNombre.setText("NOMBRES");

        txtUserNombre.setBackground(new java.awt.Color(255, 255, 204));
        txtUserNombre.setBorder(null);
        txtUserNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUserNombre.setEnabled(false);
        txtUserNombre.setOpaque(true);

        lblCedula.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCedula.setText("CEDULA");

        txtUserCedula.setBackground(new java.awt.Color(255, 255, 204));
        txtUserCedula.setBorder(null);
        txtUserCedula.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUserCedula.setEnabled(false);
        txtUserCedula.setOpaque(true);

        txtUserCategoria.setBackground(new java.awt.Color(255, 255, 204));
        txtUserCategoria.setBorder(null);
        txtUserCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUserCategoria.setEnabled(false);
        txtUserCategoria.setOpaque(true);

        lblCategoria.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria.setText("CATEGORIA");

        lblCategoria1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria1.setText("CURSO");

        txtUserCurso.setBackground(new java.awt.Color(255, 255, 204));
        txtUserCurso.setBorder(null);
        txtUserCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUserCurso.setEnabled(false);
        txtUserCurso.setOpaque(true);

        txtUserEstado.setBackground(new java.awt.Color(255, 255, 204));
        txtUserEstado.setBorder(null);
        txtUserEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUserEstado.setEnabled(false);
        txtUserEstado.setOpaque(true);

        lblCategoria2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria2.setText("ESTADO");

        btnUserSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnUserSearch.setBorder(null);

        lblUserInfo.setForeground(new java.awt.Color(255, 0, 51));
        lblUserInfo.setText("* ");

        javax.swing.GroupLayout pnlUserLayout = new javax.swing.GroupLayout(pnlUser);
        pnlUser.setLayout(pnlUserLayout);
        pnlUserLayout.setHorizontalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUserLayout.createSequentialGroup()
                        .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlUserLayout.createSequentialGroup()
                        .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUserCedula)
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUserEstado)
                            .addComponent(txtUserCurso)
                            .addComponent(txtUserCategoria)
                            .addComponent(txtUserNombre)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserLayout.createSequentialGroup()
                                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlUserLayout.createSequentialGroup()
                                        .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblUserEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtUserSearch))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUserSearch, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addContainerGap())))
        );
        pnlUserLayout.setVerticalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUserSearch))
                .addGap(12, 12, 12)
                .addComponent(lblUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCedula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCategoria1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCategoria2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pnlCreatePrestamo.add(pnlUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 510));

        javax.swing.GroupLayout formCreatePrestamoLayout = new javax.swing.GroupLayout(formCreatePrestamo.getContentPane());
        formCreatePrestamo.getContentPane().setLayout(formCreatePrestamoLayout);
        formCreatePrestamoLayout.setHorizontalGroup(
            formCreatePrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formCreatePrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCreatePrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        formCreatePrestamoLayout.setVerticalGroup(
            formCreatePrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formCreatePrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCreatePrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        formCreatePrestamo.getAccessibleContext().setAccessibleParent(pnlMain);

        setMinimumSize(new java.awt.Dimension(684, 694));
        setPreferredSize(new java.awt.Dimension(684, 694));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMain.setPreferredSize(new java.awt.Dimension(684, 694));
        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackground.setMinimumSize(new java.awt.Dimension(684, 685));
        pnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox1.setText("EN CURSO");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });
        pnlBackground.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        btnEditarUsuario.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnEditarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconBookmarkAdd.png"))); // NOI18N
        btnEditarUsuario.setText("RECEPCIONAR");
        btnEditarUsuario.setToolTipText("");
        btnEditarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEditarUsuario.setIconTextGap(10);
        btnEditarUsuario.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnEditarUsuario.setMaximumSize(new java.awt.Dimension(125, 35));
        btnEditarUsuario.setMinimumSize(new java.awt.Dimension(125, 35));
        btnEditarUsuario.setPreferredSize(new java.awt.Dimension(125, 35));
        btnEditarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarUsuarioMouseClicked(evt);
            }
        });
        btnEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUsuarioActionPerformed(evt);
            }
        });
        pnlBackground.add(btnEditarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 60, 160, 40));

        btnEliminarUsuario.setBackground(new java.awt.Color(102, 0, 0));
        btnEliminarUsuario.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnEliminarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconTrash.png"))); // NOI18N
        btnEliminarUsuario.setText("ELIMINAR");
        btnEliminarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEliminarUsuario.setIconTextGap(10);
        btnEliminarUsuario.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnEliminarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarUsuarioMouseClicked(evt);
            }
        });
        pnlBackground.add(btnEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 680, 160, 40));

        btnCrearUsuario.setBackground(new java.awt.Color(153, 255, 153));
        btnCrearUsuario.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnCrearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnCrearUsuario.setText("CREAR PRESTAMO");
        btnCrearUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCrearUsuario.setIconTextGap(10);
        btnCrearUsuario.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnCrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearUsuarioMouseClicked(evt);
            }
        });
        btnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsuarioActionPerformed(evt);
            }
        });
        pnlBackground.add(btnCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, -1, 40));

        txfSearch.setBackground(new java.awt.Color(242, 242, 242));
        txfSearch.setBorder(null);
        txfSearch.setMargin(new java.awt.Insets(0, 10, 0, 0));
        txfSearch.setOpaque(true);
        txfSearch.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txfSearchInputMethodTextChanged(evt);
            }
        });
        txfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfSearchActionPerformed(evt);
            }
        });
        txfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfSearchKeyTyped(evt);
            }
        });
        pnlBackground.add(txfSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 40));

        btnSearch.setBackground(new java.awt.Color(242, 242, 242));
        btnSearch.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.setOpaque(true);
        pnlBackground.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 40, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        pnlBackground.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 980, 550));

        pnlMain.add(pnlBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 740));

        add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 730));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {
        
        
        formCreatePrestamo.setVisible(true);

        // cargarFormCrear();
    }

    private void btnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {    }

    private void btnEditarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {
        
        // String usuario = tblUsers.getModel().getValueAt(tblUsers.getSelectedRow(), 0).toString();
        // JOptionPane.showMessageDialog(pnlUsuarioMain, usuario);
        
        // cargarFormModificar();

        new VFuncionesPrestamos().recepcionarPrestamo(jTable1);
        new VFuncionesPrestamos().mostrarPrestamos(jTable1);
        
    }

    private void btnEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {}

    private void btnEliminarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {
        
        // deleteUser();
        // mostrarUsuarios();
        new VFuncionesPrestamos().eliminarPrestamo(jTable1);
        new VFuncionesPrestamos().mostrarPrestamos(jTable1);
    }
    
    private void txfSearchInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {}

    private void txfSearchActionPerformed(java.awt.event.ActionEvent evt) {}

    private void txfSearchKeyTyped(java.awt.event.KeyEvent evt) {
        
        ((AbstractDocument) txfSearch.getDocument()).setDocumentFilter(new Validaciones.filtroAlphaNumerico());
        if (jCheckBox1.isSelected()){
            new VFuncionesPrestamos().filtrarTabla(jTable1,"EN CURSO", txfSearch.getText() );
        }else new VFuncionesPrestamos().filtrarTabla(jTable1,txfSearch.getText(),"");
        
    }

    private void btnEliminarUsuario1MouseClicked(java.awt.event.MouseEvent evt) {}

    private void btnCrearUsuario1MouseClicked(java.awt.event.MouseEvent evt) {}

    private void btnCrearUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {}

    private void btnEditarUsuario1MouseClicked(java.awt.event.MouseEvent evt) {}

    private void btnEditarUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {}

    private void txfSearch1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {}

    private void txfSearch1ActionPerformed(java.awt.event.ActionEvent evt) {}

    private void txfSearch1KeyTyped(java.awt.event.KeyEvent evt) {}

    private void txfSearch2InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {}

    private void txfSearch2ActionPerformed(java.awt.event.ActionEvent evt) {}

    private void txfSearch2KeyTyped(java.awt.event.KeyEvent evt) {}

    private void formComponentShown(java.awt.event.ComponentEvent evt) {
        
        new VFuncionesPrestamos().mostrarPrestamos(jTable1);
    }

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {}

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {
        
        if (jCheckBox1.isSelected()){
            new VFuncionesPrestamos().filtrarTabla(jTable1,"EN CURSO", txfSearch.getText() );
        }else new VFuncionesPrestamos().filtrarTabla(jTable1,txfSearch.getText(),"");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelCreatePrestamo;
    private javax.swing.JButton btnCleanFormPrestamo;
    private javax.swing.JButton btnCrearUsuario;
    private javax.swing.JButton btnCreatePrestamo;
    private javax.swing.JButton btnEditarUsuario;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnLibSearch;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JButton btnUserSearch;
    private javax.swing.JFrame formCreatePrestamo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    protected javax.swing.JLabel lblCategoria;
    protected javax.swing.JLabel lblCategoria1;
    protected javax.swing.JLabel lblCategoria2;
    protected javax.swing.JLabel lblCategoria3;
    protected javax.swing.JLabel lblCategoria4;
    protected javax.swing.JLabel lblCategoria5;
    protected javax.swing.JLabel lblCedula;
    protected javax.swing.JLabel lblCedula1;
    protected javax.swing.JLabel lblInfoFormCreatePrestamo;
    protected javax.swing.JLabel lblLibEstado;
    protected javax.swing.JLabel lblLibId;
    protected javax.swing.JLabel lblLibInfo;
    protected javax.swing.JLabel lblNombre;
    protected javax.swing.JLabel lblNombre1;
    protected javax.swing.JLabel lblTitle;
    protected javax.swing.JLabel lblTitle1;
    protected javax.swing.JLabel lblUserEstado;
    protected javax.swing.JLabel lblUserId;
    protected javax.swing.JLabel lblUserInfo;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlCreatePrestamo;
    private javax.swing.JPanel pnlLib;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlUser;
    protected javax.swing.JTextField txfSearch;
    protected javax.swing.JTextField txtLibAutor;
    protected javax.swing.JTextField txtLibCategoria;
    protected javax.swing.JTextField txtLibCodigo;
    protected javax.swing.JTextField txtLibSearch;
    protected javax.swing.JTextField txtLibTitulo;
    protected javax.swing.JTextField txtLibUbicacion;
    protected javax.swing.JTextField txtUserCategoria;
    protected javax.swing.JTextField txtUserCedula;
    protected javax.swing.JTextField txtUserCurso;
    protected javax.swing.JTextField txtUserEstado;
    protected javax.swing.JTextField txtUserNombre;
    protected javax.swing.JTextField txtUserSearch;
    // End of variables declaration//GEN-END:variables
}
