/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package biblioteca.vista;

/**
 *
 * @author arnal
 */
public class VPrestamos extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */

    public VPrestamos() {
        initComponents();
       formCreatePrestamo.setVisible(false);
      lblUserId.setVisible(false);
      lblUserEstado.setVisible(false);
      lblUserInfo.setText("");
      lblInfoFormCreatePrestamo.setText("");
      lblLibEstado.setVisible(false);
      lblLibId.setVisible(false);
      lblLibInfo.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formCreatePrestamo = new javax.swing.JFrame();
        pnlCreatePrestamo = new javax.swing.JPanel();
        lblInfoFormCreatePrestamo = new javax.swing.JLabel();
        btnCancelCreatePrestamo = new javax.swing.JButton();
        btnCreatePrestamo = new javax.swing.JButton();
        btnCleanFormPrestamo = new javax.swing.JButton();
        pnlLib = new javax.swing.JPanel();
        txtLibSearch = new javax.swing.JTextField();
        lblTitle1 = new javax.swing.JLabel();
        lblLibId = new javax.swing.JLabel();
        lblLibEstado = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        txtLibTitulo = new javax.swing.JTextField();
        lblCedula1 = new javax.swing.JLabel();
        txtLibCodigo = new javax.swing.JTextField();
        txtLibAutor = new javax.swing.JTextField();
        lblCategoria3 = new javax.swing.JLabel();
        lblCategoria4 = new javax.swing.JLabel();
        txtLibCategoria = new javax.swing.JTextField();
        txtLibUbicacion = new javax.swing.JTextField();
        lblCategoria5 = new javax.swing.JLabel();
        btnLibSearch = new javax.swing.JButton();
        lblLibInfo = new javax.swing.JLabel();
        pnlUser = new javax.swing.JPanel();
        txtUserSearch = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblUserId = new javax.swing.JLabel();
        lblUserEstado = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtUserNombre = new javax.swing.JTextField();
        lblCedula = new javax.swing.JLabel();
        txtUserCedula = new javax.swing.JTextField();
        txtUserCategoria = new javax.swing.JTextField();
        lblCategoria = new javax.swing.JLabel();
        lblCategoria1 = new javax.swing.JLabel();
        txtUserCurso = new javax.swing.JTextField();
        txtUserEstado = new javax.swing.JTextField();
        lblCategoria2 = new javax.swing.JLabel();
        btnUserSearch = new javax.swing.JButton();
        lblUserInfo = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        pnlBackground = new javax.swing.JPanel();
        checkEstado = new javax.swing.JCheckBox();
        btnRecepcionarPrestamo = new javax.swing.JButton();
        btnEliminarPrestamo = new javax.swing.JButton();
        btnCrearPrestamo = new javax.swing.JButton();
        txtSearchPrestamo = new javax.swing.JTextField();
        btnSearch = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrestamos = new javax.swing.JTable();

        formCreatePrestamo.setAlwaysOnTop(true);
        formCreatePrestamo.setLocation(new java.awt.Point(782, 186));
        formCreatePrestamo.setMinimumSize(new java.awt.Dimension(802, 680));
        formCreatePrestamo.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        formCreatePrestamo.setPreferredSize(new java.awt.Dimension(802, 680));
        formCreatePrestamo.setResizable(false);
        formCreatePrestamo.setSize(new java.awt.Dimension(802, 680));
        formCreatePrestamo.setType(java.awt.Window.Type.POPUP);

        pnlCreatePrestamo.setBackground(new java.awt.Color(255, 255, 255));
        pnlCreatePrestamo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInfoFormCreatePrestamo.setForeground(new java.awt.Color(255, 0, 51));
        lblInfoFormCreatePrestamo.setText("* ");
        pnlCreatePrestamo.add(lblInfoFormCreatePrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 780, 20));

        btnCancelCreatePrestamo.setBackground(new java.awt.Color(102, 0, 0));
        btnCancelCreatePrestamo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCancelCreatePrestamo.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelCreatePrestamo.setText("CANCELAR");
        btnCancelCreatePrestamo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelCreatePrestamo.setIconTextGap(10);
        btnCancelCreatePrestamo.setMargin(new java.awt.Insets(2, 1, 3, 14));
        pnlCreatePrestamo.add(btnCancelCreatePrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 160, 40));

        btnCreatePrestamo.setBackground(new java.awt.Color(153, 255, 153));
        btnCreatePrestamo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnCreatePrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnCreatePrestamo.setText("CREAR PRESTAMO");
        btnCreatePrestamo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCreatePrestamo.setIconTextGap(10);
        btnCreatePrestamo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        pnlCreatePrestamo.add(btnCreatePrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 590, 190, 40));

        btnCleanFormPrestamo.setBackground(new java.awt.Color(230, 230, 230));
        btnCleanFormPrestamo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCleanFormPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconMop.png"))); // NOI18N
        btnCleanFormPrestamo.setText("LIMPIAR");
        btnCleanFormPrestamo.setToolTipText("");
        btnCleanFormPrestamo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCleanFormPrestamo.setIconTextGap(10);
        btnCleanFormPrestamo.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnCleanFormPrestamo.setMaximumSize(new java.awt.Dimension(125, 35));
        btnCleanFormPrestamo.setMinimumSize(new java.awt.Dimension(125, 35));
        btnCleanFormPrestamo.setPreferredSize(new java.awt.Dimension(125, 35));
        pnlCreatePrestamo.add(btnCleanFormPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 590, 160, 40));

        pnlLib.setBackground(new java.awt.Color(255, 255, 255));

        txtLibSearch.setBackground(new java.awt.Color(245, 245, 245));
        txtLibSearch.setBorder(null);
        txtLibSearch.setMargin(new java.awt.Insets(0, 10, 0, 0));
        txtLibSearch.setOpaque(true);

        lblTitle1.setFont(new java.awt.Font("Roboto Black", 3, 24)); // NOI18N
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("SELECCIONAR LIBRO");

        lblLibId.setBackground(new java.awt.Color(255, 255, 204));
        lblLibId.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblLibId.setForeground(new java.awt.Color(255, 255, 204));
        lblLibId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLibId.setText("0");
        lblLibId.setToolTipText("");
        lblLibId.setEnabled(false);
        lblLibId.setFocusable(false);

        lblLibEstado.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblLibEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLibEstado.setText("0");
        lblLibEstado.setEnabled(false);

        lblNombre1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblNombre1.setText("TITULO");

        txtLibTitulo.setEditable(false);
        txtLibTitulo.setForeground(new java.awt.Color(0, 0, 0));
        txtLibTitulo.setBorder(null);
        txtLibTitulo.setCaretColor(new java.awt.Color(0, 0, 0));
        txtLibTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLibTitulo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtLibTitulo.setEnabled(false);
        txtLibTitulo.setOpaque(true);

        lblCedula1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCedula1.setText("CODIGO");

        txtLibCodigo.setEditable(false);
        txtLibCodigo.setForeground(new java.awt.Color(0, 0, 0));
        txtLibCodigo.setBorder(null);
        txtLibCodigo.setCaretColor(new java.awt.Color(0, 0, 0));
        txtLibCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLibCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtLibCodigo.setEnabled(false);
        txtLibCodigo.setOpaque(true);

        txtLibAutor.setEditable(false);
        txtLibAutor.setForeground(new java.awt.Color(0, 0, 0));
        txtLibAutor.setBorder(null);
        txtLibAutor.setCaretColor(new java.awt.Color(0, 0, 0));
        txtLibAutor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLibAutor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtLibAutor.setEnabled(false);
        txtLibAutor.setOpaque(true);

        lblCategoria3.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria3.setText("AUTOR");

        lblCategoria4.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria4.setText("CATEGORIA");

        txtLibCategoria.setEditable(false);
        txtLibCategoria.setForeground(new java.awt.Color(0, 0, 0));
        txtLibCategoria.setBorder(null);
        txtLibCategoria.setCaretColor(new java.awt.Color(0, 0, 0));
        txtLibCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLibCategoria.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtLibCategoria.setEnabled(false);
        txtLibCategoria.setOpaque(true);

        txtLibUbicacion.setEditable(false);
        txtLibUbicacion.setForeground(new java.awt.Color(0, 0, 0));
        txtLibUbicacion.setBorder(null);
        txtLibUbicacion.setCaretColor(new java.awt.Color(0, 0, 0));
        txtLibUbicacion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLibUbicacion.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtLibUbicacion.setEnabled(false);
        txtLibUbicacion.setOpaque(true);

        lblCategoria5.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria5.setText("UBICACION");

        btnLibSearch.setBackground(new java.awt.Color(245, 245, 245));
        btnLibSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnLibSearch.setBorder(null);

        lblLibInfo.setForeground(new java.awt.Color(255, 0, 51));
        lblLibInfo.setText("* ");

        javax.swing.GroupLayout pnlLibLayout = new javax.swing.GroupLayout(pnlLib);
        pnlLib.setLayout(pnlLibLayout);
        pnlLibLayout.setHorizontalGroup(
            pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLibLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlLibLayout.createSequentialGroup()
                        .addComponent(lblCategoria5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLibUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlLibLayout.createSequentialGroup()
                        .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlLibLayout.createSequentialGroup()
                                .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCedula1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCategoria3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLibAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLibCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLibLayout.createSequentialGroup()
                                .addComponent(txtLibSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLibSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLibLayout.createSequentialGroup()
                                .addComponent(lblLibEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLibId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(lblLibInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12))
                            .addGroup(pnlLibLayout.createSequentialGroup()
                                .addComponent(lblCategoria4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLibCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                            .addGroup(pnlLibLayout.createSequentialGroup()
                                .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLibTitulo)))))
                .addContainerGap())
        );
        pnlLibLayout.setVerticalGroup(
            pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLibLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtLibSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLibSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLibInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLibEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblLibId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCedula1)
                        .addComponent(txtLibCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLibTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNombre1)))
                .addGap(18, 18, 18)
                .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCategoria3)
                        .addComponent(txtLibAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCategoria4)
                        .addComponent(txtLibCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria5)
                    .addComponent(txtLibUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pnlCreatePrestamo.add(pnlLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 780, 250));

        pnlUser.setBackground(new java.awt.Color(255, 255, 255));

        txtUserSearch.setBackground(new java.awt.Color(245, 245, 245));
        txtUserSearch.setBorder(null);
        txtUserSearch.setMargin(new java.awt.Insets(0, 10, 0, 0));
        txtUserSearch.setOpaque(true);

        lblTitle.setFont(new java.awt.Font("Roboto Black", 3, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("SELECCIONAR USUARIO");

        lblUserId.setBackground(new java.awt.Color(255, 255, 204));
        lblUserId.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblUserId.setForeground(new java.awt.Color(255, 255, 204));
        lblUserId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserId.setText("0");
        lblUserId.setToolTipText("");
        lblUserId.setEnabled(false);
        lblUserId.setFocusable(false);

        lblUserEstado.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblUserEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserEstado.setText("0");
        lblUserEstado.setEnabled(false);

        lblNombre.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblNombre.setText("NOMBRES");

        txtUserNombre.setEditable(false);
        txtUserNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtUserNombre.setBorder(null);
        txtUserNombre.setCaretColor(new java.awt.Color(0, 0, 0));
        txtUserNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUserNombre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtUserNombre.setEnabled(false);
        txtUserNombre.setOpaque(true);

        lblCedula.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCedula.setText("CEDULA");

        txtUserCedula.setEditable(false);
        txtUserCedula.setForeground(new java.awt.Color(0, 0, 0));
        txtUserCedula.setBorder(null);
        txtUserCedula.setCaretColor(new java.awt.Color(0, 0, 0));
        txtUserCedula.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUserCedula.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtUserCedula.setEnabled(false);
        txtUserCedula.setOpaque(true);

        txtUserCategoria.setEditable(false);
        txtUserCategoria.setForeground(new java.awt.Color(0, 0, 0));
        txtUserCategoria.setBorder(null);
        txtUserCategoria.setCaretColor(new java.awt.Color(0, 0, 0));
        txtUserCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUserCategoria.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtUserCategoria.setEnabled(false);
        txtUserCategoria.setOpaque(true);

        lblCategoria.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria.setText("CATEGORIA");

        lblCategoria1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria1.setText("CURSO");

        txtUserCurso.setEditable(false);
        txtUserCurso.setForeground(new java.awt.Color(0, 0, 0));
        txtUserCurso.setBorder(null);
        txtUserCurso.setCaretColor(new java.awt.Color(0, 0, 0));
        txtUserCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUserCurso.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtUserCurso.setEnabled(false);
        txtUserCurso.setOpaque(true);

        txtUserEstado.setEditable(false);
        txtUserEstado.setForeground(new java.awt.Color(0, 0, 0));
        txtUserEstado.setBorder(null);
        txtUserEstado.setCaretColor(new java.awt.Color(0, 0, 0));
        txtUserEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUserEstado.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtUserEstado.setEnabled(false);
        txtUserEstado.setOpaque(true);

        lblCategoria2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria2.setText("ESTADO");

        btnUserSearch.setBackground(new java.awt.Color(245, 245, 245));
        btnUserSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnUserSearch.setBorder(null);

        lblUserInfo.setForeground(new java.awt.Color(255, 0, 51));
        lblUserInfo.setText("* ");

        javax.swing.GroupLayout pnlUserLayout = new javax.swing.GroupLayout(pnlUser);
        pnlUser.setLayout(pnlUserLayout);
        pnlUserLayout.setHorizontalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlUserLayout.createSequentialGroup()
                        .addComponent(lblCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUserCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUserCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUserLayout.createSequentialGroup()
                        .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlUserLayout.createSequentialGroup()
                                .addComponent(lblCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUserEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlUserLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(txtUserCedula))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserLayout.createSequentialGroup()
                                .addComponent(txtUserSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUserSearch)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUserLayout.createSequentialGroup()
                                .addComponent(lblUserEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addGroup(pnlUserLayout.createSequentialGroup()
                                .addComponent(txtUserNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        pnlUserLayout.setVerticalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlUserLayout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUserSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUserSearch)
                            .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblUserEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCedula)
                            .addComponent(txtUserCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre)
                            .addComponent(txtUserNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCategoria)
                            .addComponent(txtUserCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblCategoria1)
                    .addComponent(txtUserCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCategoria2)
                    .addComponent(txtUserEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnlCreatePrestamo.add(pnlUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 780, 260));

        javax.swing.GroupLayout formCreatePrestamoLayout = new javax.swing.GroupLayout(formCreatePrestamo.getContentPane());
        formCreatePrestamo.getContentPane().setLayout(formCreatePrestamoLayout);
        formCreatePrestamoLayout.setHorizontalGroup(
            formCreatePrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formCreatePrestamoLayout.createSequentialGroup()
                .addComponent(pnlCreatePrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        formCreatePrestamoLayout.setVerticalGroup(
            formCreatePrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formCreatePrestamoLayout.createSequentialGroup()
                .addComponent(pnlCreatePrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );

        formCreatePrestamo.getAccessibleContext().setAccessibleParent(pnlMain);

        setMinimumSize(new java.awt.Dimension(684, 694));
        setName("prestamos"); // NOI18N
        setPreferredSize(new java.awt.Dimension(684, 694));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMain.setPreferredSize(new java.awt.Dimension(684, 694));
        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackground.setMinimumSize(new java.awt.Dimension(684, 685));
        pnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkEstado.setText("EN CURSO");
        pnlBackground.add(checkEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        btnRecepcionarPrestamo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnRecepcionarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconBookmarkAdd.png"))); // NOI18N
        btnRecepcionarPrestamo.setText("RECEPCIONAR");
        btnRecepcionarPrestamo.setToolTipText("");
        btnRecepcionarPrestamo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRecepcionarPrestamo.setIconTextGap(10);
        btnRecepcionarPrestamo.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnRecepcionarPrestamo.setMaximumSize(new java.awt.Dimension(125, 35));
        btnRecepcionarPrestamo.setMinimumSize(new java.awt.Dimension(125, 35));
        btnRecepcionarPrestamo.setPreferredSize(new java.awt.Dimension(125, 35));
        pnlBackground.add(btnRecepcionarPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 160, 40));

        btnEliminarPrestamo.setBackground(new java.awt.Color(102, 0, 0));
        btnEliminarPrestamo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnEliminarPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarPrestamo.setText("ELIMINAR");
        btnEliminarPrestamo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEliminarPrestamo.setIconTextGap(10);
        btnEliminarPrestamo.setMargin(new java.awt.Insets(2, 1, 3, 14));
        pnlBackground.add(btnEliminarPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 680, 160, 40));

        btnCrearPrestamo.setBackground(new java.awt.Color(153, 255, 153));
        btnCrearPrestamo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnCrearPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnCrearPrestamo.setText("<html>NUEVO<br>PRESTAMO</html>");
        btnCrearPrestamo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCrearPrestamo.setIconTextGap(10);
        btnCrearPrestamo.setMargin(new java.awt.Insets(2, 1, 3, 14));
        pnlBackground.add(btnCrearPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 160, 60));

        txtSearchPrestamo.setBackground(new java.awt.Color(242, 242, 242));
        txtSearchPrestamo.setBorder(null);
        txtSearchPrestamo.setMargin(new java.awt.Insets(0, 10, 0, 0));
        txtSearchPrestamo.setOpaque(true);
        pnlBackground.add(txtSearchPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 40));

        btnSearch.setBackground(new java.awt.Color(242, 242, 242));
        btnSearch.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.setOpaque(true);
        pnlBackground.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 40, 40));

        tblPrestamos.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        tblPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPrestamos.setRowHeight(35);
        jScrollPane1.setViewportView(tblPrestamos);

        pnlBackground.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 980, 530));

        pnlMain.add(pnlBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 740));

        add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 730));
    }// </editor-fold>//GEN-END:initComponents
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelCreatePrestamo;
    public javax.swing.JButton btnCleanFormPrestamo;
    public javax.swing.JButton btnCrearPrestamo;
    public javax.swing.JButton btnCreatePrestamo;
    public javax.swing.JButton btnEliminarPrestamo;
    public javax.swing.JButton btnLibSearch;
    public javax.swing.JButton btnRecepcionarPrestamo;
    private javax.swing.JLabel btnSearch;
    public javax.swing.JButton btnUserSearch;
    public javax.swing.JCheckBox checkEstado;
    public javax.swing.JFrame formCreatePrestamo;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JLabel lblCategoria;
    protected javax.swing.JLabel lblCategoria1;
    protected javax.swing.JLabel lblCategoria2;
    protected javax.swing.JLabel lblCategoria3;
    protected javax.swing.JLabel lblCategoria4;
    protected javax.swing.JLabel lblCategoria5;
    protected javax.swing.JLabel lblCedula;
    protected javax.swing.JLabel lblCedula1;
    public javax.swing.JLabel lblInfoFormCreatePrestamo;
    public javax.swing.JLabel lblLibEstado;
    public javax.swing.JLabel lblLibId;
    public javax.swing.JLabel lblLibInfo;
    protected javax.swing.JLabel lblNombre;
    protected javax.swing.JLabel lblNombre1;
    protected javax.swing.JLabel lblTitle;
    protected javax.swing.JLabel lblTitle1;
    public javax.swing.JLabel lblUserEstado;
    public javax.swing.JLabel lblUserId;
    public javax.swing.JLabel lblUserInfo;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlCreatePrestamo;
    private javax.swing.JPanel pnlLib;
    private javax.swing.JPanel pnlMain;
    public javax.swing.JPanel pnlUser;
    public javax.swing.JTable tblPrestamos;
    public javax.swing.JTextField txtLibAutor;
    public javax.swing.JTextField txtLibCategoria;
    public javax.swing.JTextField txtLibCodigo;
    public javax.swing.JTextField txtLibSearch;
    public javax.swing.JTextField txtLibTitulo;
    public javax.swing.JTextField txtLibUbicacion;
    public javax.swing.JTextField txtSearchPrestamo;
    public javax.swing.JTextField txtUserCategoria;
    public javax.swing.JTextField txtUserCedula;
    public javax.swing.JTextField txtUserCurso;
    public javax.swing.JTextField txtUserEstado;
    public javax.swing.JTextField txtUserNombre;
    public javax.swing.JTextField txtUserSearch;
    // End of variables declaration//GEN-END:variables
}
